default:pointer_refer.o
	g++ -std=c++11 -o pointer_refer.t pointer_refer.o

pointer_refer.o:pointer_refer.cc
	g++ -std=c++11 -c pointer_refer.cc

.PONY:clean
clean:
	-rm pointer_refer.o pointer_refer.t